### ISSUE TITLE
Remove unneeded conditional

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-vc-verifier#13]
https://github.com/digitalbazaar/bedrock-vc-verifier/blob/master/lib/index.js#L202

Static analysis indicated to me that `firstCredentialResult` is always true as it assigned to some truthy value directly above.

**Comment by JSAssassin** [comment]
Addressed here fb94c8c

**Comment by JSAssassin** [comment]
Closing, implemented.
