### ISSUE TITLE
Simplify/Fix Regex

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-vc-verifier#15]
https://github.com/digitalbazaar/bedrock-vc-verifier/blob/master/lib/documentLoader.js#L59

This regex uses pole/pipe characters `|` as if they were an `OR` operator in the character class which is incorrect.  There is no need for a delimiter between characters in the character class.  The negative effect is that `|` is being included in the character class which is unwanted as `|` must be encoded if it is to be included in a URL.  Infact, `|` is being included in the character class 3 times.

The simplified version is:
```
const splitRegex = /[;\/\?#]/;
```

See the description on the right hand side
correct: https://regex101.com/r/lhbzSK/1
incorrect: https://regex101.com/r/R0i8Pn/1

**Comment by JSAssassin** [comment]
Addressed here 949ae80

**Comment by JSAssassin** [comment]
Closing, implemented.
